services:
  - type: web
    name: filamento
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PORT
        value: "10000"
    disk:
      name: filamento-data
      mountPath: /var/data
      sizeGB: 1
